#pragma once

using namespace ATL;

template <class T>
class CProxy_IRDBSInterfaceEvents : public IConnectionPointImpl<T, &__uuidof( _IRDBSInterfaceEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
